server:
  port: 8091

spring:
  application:
    name: fraud
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: '${PSQL_URL}'
    username: '${DB_USER}'
    password: '${DB_PASS}'
  sql:
    init:
      platform: postgres
eureka:
  client:
    service-url:
      defaultZone: '${EUREKA_URL}'
