{{ $top := . }}
{{ range .Values.pingnInstances }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .name }}"
  labels:
    {{- include "pingn.labels" $ | nindent 4 }}
spec:
  {{- if not $top.Values.autoscaling.enabled }}
  replicas: {{ $top.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pingn.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $top.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        base-app: {{ include "pingn.fullname" $ }}
        app: {{ .name }}
        {{- include "pingn.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $top.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pingn.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $top.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .name }}
          securityContext:
            {{- toYaml $top.Values.securityContext | nindent 12 }}
          image: "{{ $top.Values.image.repository }}:{{ $top.Values.image.tag | default $top.Chart.AppVersion }}"
          imagePullPolicy: {{ $top.Values.image.pullPolicy }}
          livenessProbe:
             httpGet:
               path: /
               port: http
          env:
            - name: PORT
              value: "{{ $top.Values.pingn.port }}"
            {{- if .env }}
              {{- toYaml .env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $top.Values.pingn.port }}
              protocol: TCP
          resources:
            {{- toYaml $top.Values.resources | nindent 12 }}
      {{- with $top.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $top.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $top.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

{{- end }} {{/* end range */}}
