apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "pingn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    base-app: {{ include "pingn.fullname" . }}
    app: postgres
